### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by wagnerm** [wagnerm/plex_live_search#8]
- [ ] search all categories and and allow category filtering
- [ ] fix local caching
- [ ] handle request errors
- [ ] document plex provider or detect it
